name: Main CI Checks

on:
  pull_request:
  push:
      branches:
        - master
        - multiple-ui5-apps

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: NPM Install
      run: npm ci 
      
  eslint:
    
    runs-on: [ubuntu-latest]
    name: ESLint
    needs: [build]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: NPM Install
      run: npm ci --no-audit --prefer-offline
    - name: ESlint Runner Action
      uses: tinovyatkin/action-eslint@v1
      with:
        # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        check-name: eslint
